kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: pod-kill
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: greeting
  mode: one
  action: pod-kill
  gracePeriod: 0